[package]
name = "mek_calculator"
version = "0.2.0"
edition = "2021"
description = "MEK reactor and boiler properties calculator - internationalized version"
license = "GPL-3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dialoguer = "0.10.3"
